### ISSUE TITLE
Question - how does a stdout consumer know when the JSON has ended?

### ISSUE THREAD

**Issue by BroadcastGames** [erkyrath/remglk#10]
Often JSON is encountered with HTTP page transactions where the header of the page tells you the total length of the page before you even start to parse the text from JSON into objects.  Even with WebSockets for 'live' sending of data - you tend to send the entire JSON string (even of several kilobytes of content to repaint an entire screen) as one big 'chunk' of data before it gets to parsing.

With RemGlk I find myself dealing with a situation where I'm using readline() on stdout and I'm finding I don't known when the virtual machine has gone idle waiting on input from the client to return.  I could make structure assumptions such as "input is always near the end", but that's the kind of assumption that isn't always good. My thoughts turn to the protocol of the environment.

remote-if-demo Python code seems to share the same problem and I see the comment "We accumulate output until it's a complete JSON message" - does it keep re-parsing after every newline the partial JSON until it validates? Failing 23 times until it gets the 24th line it needs?

Internally RemGlk must know when it is 'done sending' as the final JSON ("}") block close is sent.  Could some meta-information be sent to indicate end-of-publish such as blank line? (empty lines are how http protocol knows when to shift form header to main content which is why that came to mind, reference: https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html section 4.1 )

Alternate to a blank line, could newline not be sent until the final close? One really long line?

A blank line wouldn't disturb JSON parsing I think. Also maybe this could be a compile ifdef option?

**Comment by erkyrath** [comment]
> "We accumulate output until it's a complete JSON message" - does it keep re-parsing after every newline the partial JSON until it validates?

Yes. This turns out to work fine, and I don't want to put further constraints on the JSON formatting of the protocol stream.

**Comment by erkyrath** [comment]
Although I can see the convenience of adding a blank line, now that I think about it.

I'm willing to try this, but you'll have to get back to me if the system produces a blank line in the middle of the JSON output. I don't think it does, but it's not something I was careful about while working.

**Comment by BroadcastGames** [comment]
Thank you. Have a good weekend!

**Comment by BroadcastGames** [comment]
Observaton: rgmisc.c/gli_display_error and gli_display_warning could use the extra 'blank line' treatment

**Comment by erkyrath** [comment]
Good point.

**Comment by BroadcastGames** [comment]
In practice, this is working really well.
