### ISSUE TITLE
window type grid, newline as first character in JSON 'text' of line 0

### ISSUE THREAD

**Issue by BroadcastGames** [erkyrath/remglk#11]
You can almost see this issue on the documentation page _Adventure_ sample output:

http://www.eblong.com/zarf/glk/remglk/docs.html

Even thought the window is defined as having a "height" of 1 line, and this is line 0, the line actually starts with a newline character (char[0]) and would technically require two lines:

     { "line":0, "content":[{ "style":"normal", "text":" At End Of Road
     Score: 36    Moves: 1      "}]}

It is a character before the word "At".  Is this some quirk with Glk's concept that all status lines must have a blank line at start if less than two, or just an accidental newline that RemGlk is inserting?

For clarity: I did encounter this 'first char is newline' on Git interpreter linked with RemGlk using advent.blb on the latest Github source of RemGlk and Git. I was trying to track down why my status line kept coming out two lines in height.

**Comment by erkyrath** [comment]
The first character of that status line output is a space, not a newline. The room name starts in the second column, due to the I6 library code that invokes `MoveCursor(1, 2)`. (That's row, column in 1-based coordinates.) Therefore a space appears before the "A".

**Comment by BroadcastGames** [comment]
ok, thank you.  Maybe citing the doc was a bad idea. Because with a Git + advent.blb  the output isn't identical to the docs, because it has "Moves: 1" also in the status line.

This exact story file: http://mirror.ifarchive.org/if-archive/games/glulx/advent.blb md5sum: 8e3ace47c395bf1acd4c5f02dd6befa3

I'm using a somewhat modified stdout on Android and I guess it's possible it's altering this one character - but I've run thousands of story lines through RemGlk and it would seem odd to pick this exact textgrid line every time in different stories to be a newline. 

I spent at least 3 days getting stdin to be reliable on all the models of test phones I had.  I guess I'm going to have to add a string hex dump down in the RemGlk C code to a file or something and see if I can figure out how I'm getting a newline only on line 0 of grid windows.

**Comment by erkyrath** [comment]
I have been testing with glulxe rather than git. 

There should never be a newline in the text line data of any window at all. I'd say it was a bug in git, but it shouldn't be possible for remglk to output that, really.

**Comment by BroadcastGames** [comment]
ok, sounds like stdout writing or reading corruption on my part. I'll close and re-open if I find otherwise. Thank you.

**Comment by erkyrath** [comment]
Ok. I just re-tested it with git+remglk, and got the same result. That section of the output looks like

     {"id":21, "lines": [
      { "line":0, "content":[{ "style":"normal", "text":" At End Of Road                                      Score: 36    Moves: 1      "}]}
     ] },

**Comment by BroadcastGames** [comment]
ok, I found a bug in my code that was adding the 81st char before the char1 space. Sorry about this. Thanks for looking into it.
