### ISSUE TITLE
revgrid option implementation

### ISSUE THREAD

**Issue by BroadcastGames** [erkyrath/remglk#13]
Code reference: https://github.com/erkyrath/remglk/blob/master/main.c#L208

Option is in help, but is it implemented in the code?  RIght now the text grid for status has style 'normal' - was your thought to set this to a 'reverse' when that line goes out?  That wold work for me.

**Comment by erkyrath** [comment]
No, remglk has no revgrid option. I originally created remglk by cloning glkterm, long ago, and I accidentally left that line in the help text. It has now been removed.

Remglk does not make any text style decisions at all; it just passes the window information over to the display layer. So there's no place in it for "reverse grid".
