### ISSUE TITLE
developer question about glk_window_struct

### ISSUE THREAD

**Issue by BroadcastGames** [erkyrath/remglk#15]
Hope you are having a good holiday.

I'm trying to wrap my brain around glk_window_struct and why it has a single value for style and hyperlink. Can a window itself be a hyperlink source (clicking anywhere on the window) - and how does a single style make sense in context of a window?  Or does that relate to style of the window such as  Border/NoBorder hint? Thank you.

**Comment by erkyrath** [comment]
The style and hyperlink values in glk_window_struct are the *most recent* values (set with glk_set_style and glk_set_hyperlink on that window's stream). They get applied to all text printed to the window. It's that text that the user sees as having the style/link attributes.

**Comment by BroadcastGames** [comment]
Ok, thank you. That's how I also ended up doing z-code color and wanted to make sure that the window object itself' wasn't a hyperlink & style target.
