### ISSUE TITLE
Sensory Jam on latest checkout, "look at photograph" in The Visual Gallery

### ISSUE THREAD

**Issue by BroadcastGames** [erkyrath/remglk#19]
Latest master code, except for the one color line changed from https://github.com/erkyrath/remglk/commit/4ca002581cc95132f7046d4682b3969e1c7e4c65

sensory.blb from http://ifdb.tads.org/viewgame?id=0ulrnusrwihmwefi  - Using this init:

    { "type": "init", "gen": 0, "metrics": { "width":124, "height":28 }, "support": [ "timer", "hyperlinks", "graphics", "graphicswin" ] }

I end up with this stanza:

	{"type":"update", "gen":3,
	"windows":[
	{ "id":39, "type":"graphics", "rock":210,
	"graphwidth":124, "graphheight":27,
	"left":0, "top":1, "width":124, "height":27 },
	{ "id":33, "type":"grid", "rock":202,
	"gridwidth":124, "gridheight":1,
	"left":0, "top":0, "width":124, "height":1 },
	{ "id":30, "type":"buffer", "rock":201,
	"left":0, "top":28, "width":124, "height":0 }
	],
	"content":[
	{"id":39, "draw": [
	{"special":"fill", "x":0, "y":0, "width":124, "height":27, "color":"#808080"},
	{"special":"image", "image":0, "width":125, "height":180, "x":0, "y":-76, "url":"file:///sdcard/blorbA/pict-0.jpeg"}
	] },
	{"id":33, "lines": [
	{ "line":0, "content":[{ "style":"normal", "text":" The Visual Gallery                                                                              Score: 0     Moves: 3      "}]}
	] },
	{"id":30, "text": [
	{"append":true, "content":[{ "style":"input", "text":"look at photograph"}]},
	{"content":[{ "style":"normal", "text":"It's not very good. Whoever took it must have been an amateur. And the subject isn't particularly fetching either."}]},
	{},
	{"content":[{ "style":"normal", "text":">"}]}
	] }
	],
	"input":[
	{"id":30, "gen":3, "type":"line", "maxlen":256 }
	]}

The graphics window ends up talking all but one line and the textbuffer set to zero lines. In contrast, Gargoyle on Ubuntu 16.10 shows what seems to be 12 lines fixed for the graphics window at the top.  Thank you.

**Comment by curiousdannii** [comment]
`{ "width":124, "height":28 }` looks like character sizes, but they will be interpreted as pixels. sensory.inf doesn't have any fancy window code, it just tries to open a graphics window of height 200px, and so naturally it will take up all 27 remaining pixels.

**Comment by BroadcastGames** [comment]
Re-reading this from the top, I didn't even catch the **"y":-76** in there. Is that supposed to be a valid value, outside the Glk window ?

**Comment by curiousdannii** [comment]
Yes, you can position an image outside the window. It's centering the image vertically.

**Comment by BroadcastGames** [comment]
Windows are positioned with Top/Left... are you saying images are positioned based on their center? Or the center of the window?

**Comment by curiousdannii** [comment]
No, the x and y params are the top and left, but it's up to the game to determine which position it will use. See the [RedrawPaintingWin function in sensory.inf](http://ifarchive.jmac.org/if-archive/games/source/inform/sensory.inf).

If you resize Gargoyle to be only 28 pixels high then you'll see the same results.

**Comment by BroadcastGames** [comment]
ok, I'll send along the newer init format. Going to start with classic VGA graphics adapter 80x24 numbers

        { "type": "init", "gen": 0, "metrics": { "width":720, "height":400, "charwidth":9, "charheight":16 } }

**Comment by BroadcastGames** [comment]
Thank you for the help Dannii, this put the train back on the track.

**Comment by curiousdannii** [comment]
Happy to help :)
