### ISSUE TITLE
graphic window, fill outside bounds of window

### ISSUE THREAD

**Issue by BroadcastGames** [erkyrath/remglk#25]
Studying the JSON output of Alabaster on Glulxe interpreter, I noticed it seems to be giving fill numbers that would go outside the window if extra calculation aren't done to prevent that. is it possible that RemGlk do the maths on these?

Story data file: http://mirror.ifarchive.org/if-archive/games/glulx/Alabaster.gblorb

If you make the random window match up to 24 for input, JSON input:

	{ "type": "init", "gen": 0, "metrics": { "width":720, "height":400, "charwidth":9, "charheight":16 }, "support": [ "timer", "hyperlinks", "graphics", "graphicswin", "sound" ] }

	{"type":"char","gen":1,"window":24,"value":" "}

	{"type":"line","gen":2,"window":24,"value":"go west"}

Here is what you get out RemGlk to define the left graphics window:

	{"type":"update", "gen":1,
	 "windows":[
	 { "id":27, "type":"graphics", "rock":200,
	   "graphwidth":180, "graphheight":400,
	   "left":0, "top":0, "width":180, "height":400 },
	 { "id":24, "type":"buffer", "rock":201,
	   "left":180, "top":0, "width":540, "height":400 }
	 ]

Later, down in update 3, you get graphics JSON like this:

	{"type":"update", "gen":3,
	 "content":[
	 {"id":27, "draw": [
	{"special":"fill", "x":0, "y":0, "width":180, "height":400, "color":"#FFFFFF"},
	{"special":"image", "image":20, "width":60, "height":156, "x":0, "y":0, "url":"http://localhost:4000/static/resource/pict-20.png"},
	{"special":"image", "image":20, "width":60, "height":156, "x":60, "y":0, "url":"http://localhost:4000/static/resource/pict-20.png"},
	{"special":"image", "image":20, "width":60, "height":156, "x":120, "y":0, "url":"http://localhost:4000/static/resource/pict-20.png"},
	{"special":"image", "image":23, "width":90, "height":234, "x":0, "y":0, "url":"http://localhost:4000/static/resource/pict-23.png"},
	{"special":"image", "image":23, "width":90, "height":234, "x":90, "y":0, "url":"http://localhost:4000/static/resource/pict-23.png"},
	{"special":"image", "image":3, "width":142, "height":220, "x":0, "y":180, "url":"http://localhost:4000/static/resource/pict-3.png"},
	{"special":"image", "image":14, "width":162, "height":400, "x":9, "y":0, "url":"http://localhost:4000/static/resource/pict-14.png"},
	{"special":"fill", "x":0, "y":0, "width":9, "height":400, "color":"#FFFFFF"},
	{"special":"fill", "x":0, "y":0, "width":180, "height":0, "color":"#FFFFFF"},
	{"special":"fill", "x":171, "y":0, "width":180, "height":400, "color":"#FFFFFF"},
	{"special":"fill", "x":0, "y":400, "width":180, "height":400, "color":"#FFFFFF"}
	 ] }

The first "fill" is a clear of the canvas.  It is these last two "fill" that are the topic. If the window has a bounds of "graphwidth":180, "graphheight":400, these fills are basically saying width/height of the full window, but using x and y offsets.

**Comment by erkyrath** [comment]
The original Glk spec allows for negative position coordinates. GlkOte accepts drawing commands that fall outside the window coordinates, either because X/Y are negative or W/H are too large. And, as you note, games send such commands.

Therefore, it makes sense to treat such commands as legal.

(Fills and images are clipped to the graphics window size.)
