### ISSUE TITLE
[Not an issue] Very confused and clueless newbie developer wondering how session data is maintained with RemGlk

### ISSUE THREAD

**Issue by GwynethLlewelyn** [erkyrath/remglk#39]
Hi there,

I apologise for asking such a trivial and possibly completely stupid (a. k. a. clueless) question.

I've been reading all information I could find on the whole Glk ecosystem in search of what I thought that would be a reasonably simple question: in environments with multiple users playing a remotely stored game (each playing by themselves, of course, not simultaneously), how does RemGlk know which data to send to each?

Essentially what I wish to do is to launch RemGlk with a game file, wrap it into some middleware that communicates via stdin/stdout, and present a front-end for that middleware, where, say, users would log in, have their own profiles, who knows, a forum to discuss progress on the game — and an area where they can continue to play their current game. There is just one RemGlk process running. What information must the middleware pass to RemGlk so that it knows it's talking with 'Player X' (possibly at generation N) and not 'Player Y' (possibly at generation M)?

When looking at all the available information, I'm scratching my head in confusion. Apparently, deep inside the GlkOte code, there are references being made to a `sessionID`, which _could_ be what I'm looking for. However, these are just mentioned in passing and not used by anything that I could find.

The best source for some clues on how to achieve this seems to be the [remote-if-demo](https://github.com/erkyrath/remote-if-demo/), which profusely scatters `sessionID`s all over the place and even kindly lets you know which one is yours (when you launch the demo game). While I [currently am unable to set this environment up](https://github.com/erkyrath/remote-if-demo/issues/2), as well as being quite unfamiliar with Python (and not really making the effort of becoming proficient in it...) in any case, the Remote IF Demo clearly states (or doesn't it?) that for each player a _new_ game is launched until memory is exhausted. In other words, as far as I can understand the code, the `sessionID` exists only at the middleware side of things (the Python code); it is not passed to RemGlk at all (or is it?), but rather for each player a different instance is forked; the Python code assigns each randomly generated `sessionID` to a specific player and, in turn, assigns that `sessionID` to a specific instance.

At least in theory, it should be possible to pre-launch, say, a dozen instances of RemGlk, and allow 12 different players to be playing at the same time; then it would be a matter of juggling these instances around, as new players come in, others quit or abandon the game, and so forth. Such code has not been developed but is certainly a theoretical possibility. However, even taking into account that RemGlk has a very small footprint (merely 450K or so on macOS Big Sur) which would be page-shared in memory across multiple identical forks anyway, it seems a rather messy way to set up such an environment.

I suppose I was expecting to have some kind of 'current state' pointer (into what theoretically can be seen as being a finite state machine), and, somehow, assign each player to the current state they're in; that way, every time RemGlk is contacted, you'd pass that pointer to it, and the VM would continue to run from that point onwards. Different players would just be on different states, but knowing the pointer to their state should be enough to configure the state machine accordingly; thus, the Glk engine would not really have a concept of 'different players', just of different states, and have an internal graph depicting state changes.

Now I'm aware that you _can_ load RemGlk with a _save file_ every time it runs, thus, for all purposes, 'initialising' the whole game for a specific player until a certain state is reached, wait for some input, switch to the next state, and save the whole game again. That's a possibility, but it seems to me that it's not a good idea for a system that is supposed to simultaneously serve several dozens (thousands?) of simultaneous users. I'm pretty sure it has its use in very specific areas, but I don't think it applies to my personal case.

So... all I'm left with seems to be the 'multiple instance forking' solution, and — possibly — worry about a system allocating a pool of RemGlk-enabled VMs according to demand. Is that correct? Am I seeing the whole picture here, or overseeing a simple and obvious solution?

(Note that an alternative would be embedding the whole C code inside my own code, and running it on multiple threads, as opposed to fully-blown, independent processes. That would at least save a lot of resources. However, I'm afraid that this will be quite a bit beyond my own meagre abilities.)

Thank you in advance for any insights!

**Comment by erkyrath** [comment]
Hi! Sorry that this is messy. RemGlk is the result of thinking of a lot of *possible* use cases, most of which never got beyond the prototype stage.

I think what you're tripping over is the idea of different users having different games but the same RemGlk process. This isn't going to work because the underlying VM is *already* written with the assumption of "one player per process". That is, if you look at the Glulxe source code, it keeps the VM state in global variables. So when you link that against RemGlk, there's no point in having a way for multiple players to connect.

(You might want multiple players to connect to *the same game*. That is, a shared display state that everybody can see and anybody can send a command to. This is workable if you assume that every viewer is up to date -- that is, they're all on the current generation -- except that if someone joins, they've got nothing and require a full update.)

> Now I'm aware that you can load RemGlk with a save file every time it runs, thus, for all purposes, 'initialising' the whole game for a specific player until a certain state is reached, wait for some input, switch to the next state, and save the whole game again. That's a possibility, but it seems to me that it's not a good idea for a system that is supposed to simultaneously serve several dozens (thousands?) of simultaneous users.

On the contrary, if I understand your situation, it's meant for exactly that. The idea would be to have a web app that maintains a session for each player, and then launch RemGlk+VM every time a command comes in, using the `-singleturn` argument. That is, RemGlk always runs as a momentary handler -- it's never blocked waiting for input. 

With this setup, the scaling is by the number of commands received per second, not by the number of simultaneous users. In theory, this should be much better. But, as I said, it hasn't been tried in real life.

**Comment by GwynethLlewelyn** [comment]
Hm! 🤔

_/me \*scratches head\*_ 🤨

O-kay. I think I've grokked it; as said, I haven't delved too deep into the Glulxe code — enough to _think_ that it _might_ only support a single player (1 player = 1 VM), but I wasn't _sure_ if that was really the case or if I was just missing something very obvious. Thanks so much for the clarification! 🙏

In a way, it makes my middleware code so much easier, since instead of worrying about handling multiple connections to one instance of RemGlk+VM, I just fork a new process and connect stdin/stdout to it. Essentially I just need to track down which savefile is associated with each player. I'm aware that's a very rough way of describing it, but I _think_ it should work. Sort of quick & dirty, but it should be fine.

A slight variant that ought to be a little more performant is to keep persistent connections with each game instance. I don't need to worry about blocking issues — technically speaking, there will be a lightweight thread communicating with each game, and there's no problem in having them all blocked for input. The idea is that keeping a persistent, blocking connection on a long-term process via a lightweight thread is far cheaper in terms of operating system resources than constantly forking new processes and killing them immediately afterwards. It's not just CPU + memory, which, granted, may not be significant (unless there are _millions_ of players, of course... not my use case). It's also constantly dumping savefiles and loading them again — that's a lot of wasteful disk I/O, IMHO... and while you avoid the _communications_ block, you'll have blocking at the disk I/O level, so it's basically a similar issue (it might be argued that contemporary file systems are far superior at dealing with such situations than whatever crude hack can be made by us newbies in the vague attempt to squeeze a bit more performance out our already-overloaded servers...).

Granted, the savefiles could get saved to a memory-based temporary filesystem... everything would work fine until the server reboots. Or, alternatively, I guess that it could be possible to store the savefiles on a [Redis](https://redis.io/) or [`memcached`](https://www.memcached.org/) server instead.

Lots to think about!

I'm closing this not-issue because I consider myself answered 😃

**Comment by curiousdannii** [comment]
Another option would be to use one of the JavaScript Glulx interpreters, which happily run side by side.

**Comment by GwynethLlewelyn** [comment]
> Another option would be to use one of the JavaScript Glulx interpreters, which happily run side by side.

Aye, I also thought about that approach. It's a possibility, although, mostly due to my irrational beliefs, I still trust an application natively compiled in good, old C more than anything written in JavaScript... I'm still stuck with the mental image that JavaScript is something you use to make web pages look nicer, while C, well, that's what you use to write mission-critical operating systems...

I _know_ it's irrational and does not correspond to the reality of what can be done with JavaScript in 2021!

Nevertheless, at this phase, I'm not completely discarding your suggestion. _If_ my endpoints were web browsers, I think I'd give it a try; but they aren't — my middleware will connect Glk to a virtual world, and, although it uses HTTP(s) for communications with the 'outside world', it has several limitations (mostly to prevent abuse), namely, even sending JSON back and forth is 'too expensive' (so to speak), and an even terser format is usually preferred. The virtual world does _not_ use HTML or JavaScript; it has its own scripting language (vaguely inspired in JS, but fully event-oriented, even more so than JS). Anyway, it's just another layer of complexity to place on top of Glk 😁
