### ISSUE TITLE
Return const char* from glkunix_fileref_get_filename

### ISSUE THREAD

**Issue by cspiegel** [erkyrath/remglk#45]
The `glkunix_fileref_get_filename` function returns `char *`, but is returning a pointer to data that continues to be owned by the Glk  implementation.  For this reason the garglk extension `garglk_fileref_get_name` returns `const char *`.  I'd like to adopt the remglk name and deprecate garglk's name, but they do slightly differ in the return type.

Can the return type of `glkunix_fileref_get_filename` be switched to `const char *`?  I realize this may cause compilation failure/diagnostics in existing end-user code, but I suspect that there aren't too many users of this specific API function, and the changes required to adapt to it, if any, are minimal.

**Comment by erkyrath** [comment]
It's kind of fugly to put *exactly one* `const` into a codebase. It raises reasonable confusion about whether all the other usages of `char *` are mutable. (Hint: no, they're not.) 

However, this function is already a hole drilled specifically for the emglken client, so it doesn't have to be all that consistent. 

Lemme ping @curiousdannii ... If it's not going to cause a problem for emglken, I'm fine with this change.

**Comment by curiousdannii** [comment]
I don't know anything about `const` in C. But I can test whatever changes you want to make.

**Comment by erkyrath** [comment]
I think you just have to change the return type of garglk_fileref_get_name() to `const char *` when the compiler complains about it. I only see that call being used as an argument to fopen(), strcpy(). and strdup(), all of which are compatible with `const char *`.
