### ISSUE TITLE
Bad echoing of Latin-1 characters in line input

### ISSUE THREAD

**Issue by erkyrath** [erkyrath/remglk#51]
If you're accepting (non-unicode) line input, and glk_set_echo_line_event(TRUE), and the input contains characters in the range 0x80-0xFF, they come out as question marks in the JSON update.

Input:

```
{ "type":"line", "gen":1, "window":20, "value":"jeté" }
```

Output:

```
 {"id":20, "text": [
  {"append":true, "content":[{ "style":"input", "text":"jet?"}]},
   ...
```

**Comment by erkyrath** [comment]
The problem turns out to be this stanza:

```
for (ix=0; ix<len; ix++) {
    glui32 ch = ((char *)inbuf)[ix];
    win_textbuffer_putchar(win, ch);
}
```

You get a signed char, which is cast to a glui32 value like 0xFFFFFFE9, and then putchar() doesn't recognize it as Latin-1.

Fix is to say 

```
    glui32 ch = ((unsigned char *)inbuf)[ix]; 
```

**Comment by erkyrath** [comment]
Fixed: https://github.com/erkyrath/remglk/commit/388611dc1a22768acaaa771aec5cce41947a987b

**Comment by erkyrath** [comment]
To demonstrate this bug: load up Lectrote, set the Glulx interpreter preference to "Glulxe" or "Git", launch Advent.ulx, and type `äëïöü` as a command input. The characters turn to `?????` when you hit Enter.

**Comment by stormi** [comment]
Thanks for fixing it this fast!
