### ISSUE TITLE
JSON escaping format with zracer.z5 and fizmo-remglk

### ISSUE THREAD

**Issue by BroadcastGames** [erkyrath/remglk#7]
The opening screen of zracer.z5 has a lot of forward and backwards slashes.  GlkOte ends up showing this error: `Server error: parsererror: SyntaxError: Unexpected token in JSON at position 4096` on Chrome browser.  Story file is here: http://ifdb.tads.org/viewgame?id=tnljfhvnzvybysqt

I'm guessing that the JSON isn't correctly formed?

**Comment by BroadcastGames** [comment]
I had the Python Turonado server code print what it was sending and it looks to me like the generated JSON is broken here on line 46:

`  { "line":45, "content":[{ "style":"normal", "text":"                                                  /      /|/////\\   /|     /| /|       /|______| /|           "}]},

  { "line":46, "content":[{ "style":"normal", "text":"                             
                    /       /|     /\\  /|     /| /|       /|//////  /|           "}]},

  { "line":47, "content":[{ "style":"normal", "text":"                                                /        /|      /\\ /|     /| /|       /|        /|           "}]},

` 

Maybe the JSON being broken right at the 4096 character is a hint of a 4K string buffer that's not being used correctly?

**Comment by BroadcastGames** [comment]
Is **content line 22** also showing the odd newline in the middle?  So line 22, line 46 both being munged and a reference to character 4096? Is there a 4096 or 8192 buffer somewhere in this C code that's not recycling correctly?

**Comment by erkyrath** [comment]
I have tested this with Fizmo+RemGlk and I don't see any invalid output. I wasn't testing with GlkOte; I was feeding the output into regtest.py (see https://github.com/erkyrath/plotex) which also parses JSON. I simulated the input sequence H (help), space (to continue), Q (quit), Y (yes quit) and got valid JSON output.

There is no buffer defined as 4096 bytes in RemGlk. There are buffers that start at 64 bytes and increase as needed, so they could be 4096 bytes or longer at some point, but there is no distinguished value where they might run out.

(Fizmo 0.7.3, RemGlk 0.2.3.)

**Comment by erkyrath** [comment]
(And yes, the regtest.py script would detect and complain about an extra newline of the sort you're describing.)

**Comment by BroadcastGames** [comment]
Thank you for looking. So, now I have a mystery to solve. I'll close this for now.

**Comment by erkyrath** [comment]
I will try setting up the tornado/glkote framework and see if anything changes.

**Comment by BroadcastGames** [comment]
I'm still working on this problem. racer.z5 shows it pretty quickly. Now I'm starting to suspect a null is being output by a printf somehow and that's what is causing me a lot of grief with stdin/stdout. When I got timers implemented - all hell breaks loose in racer.z5 with the massive stream. Trying to wrap printf to see if I can figure it out. Still working on it.
