### ISSUE TITLE
Request: Make work (Android.mk & Frotz) for other Interpreters

### ISSUE THREAD

**Issue by BroadcastGames** [erkyrath/remglk#8]
EDIT: I mean to say 'Frotz' on the subject.

Open request to anyone who knows C make conventions more than I do. I will try to hack these, but would also openly invite it done correct instead of my novice results.  There are two general requests:

1. I would like to be able to build RemGlk with Android.  The 'old' standard for this is an Android.mk file. For an example of this, look at Son of HunkyPunk's Android.mk for garglk: https://github.com/retrobits/son_of_hunkypunk/blob/master/app/src/main/jni/garglk/Android.mk - in that tree you will see side-by-side examples of standard desktop Makefile and Android.mk, for example Git interpreter: https://github.com/retrobits/son_of_hunkypunk/tree/master/app/src/main/jni/git

2. C Makefile so we link other interpreters to RemGlk on desktop systems.  For alternate Glk example, nanoglk knows how to compile and link Frotz: https://github.com/BroadcastGames/nanoglk/blob/master/Makefile#L57 to link with itself.  So far, I've managed to get Glulxe, Git, and Fizmo to link with RemGlk.   I see that GarGlk has an extensive set, but uses a different make system? https://github.com/garglk/garglk/tree/master/terps/

Thank you.

**Comment by erkyrath** [comment]
The Makefiles for cheapglk/remglk/etc are clunky, but I can't usefully support versions for every possible build system so I am leaving them as they are.

**Comment by BroadcastGames** [comment]
Follow-up, this worked fine for me in Android NDK 12b as a Android.mk makefile that can be inserted into Twisty or Son of Hunky Punk's tree structure with 'remglk' as a parallel directory to the other interpreter file directories and alternate glk options (nanoglk or cheapglk for example).

`LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE    := remglk
LOCAL_SRC_FILES := main.c rgevent.c rgfref.c rggestal.c \
                     rgdata.c rgmisc.c rgstream.c rgstyle.c \
                     rgwin_blank.c rgwin_buf.c rgwin_grid.c rgwin_pair.c rgwindow.c \
                     rgschan.c rgblorb.c cgunicod.c cgdate.c gi_dispa.c gi_blorb.c
LOCAL_CFLAGS	:= -DANDGLK 

include $(BUILD_STATIC_LIBRARY)
`
