### ISSUE TITLE
Control-C results in RemGlk resending the JSON with incremented gen before exiting

### ISSUE THREAD

**Issue by BroadcastGames** [erkyrath/remglk#9]
I noticed this with latest fizmo linked to RemGlk running .z stories. Didn't test with other interpreters.  If I send the init, get the first screen, and RemGlk is waiting for the remote to send JSON and do a control-c to stdin to 'exit the app', it increments the gen= and resends the last 'screen of JSON like a redraw then seems to do a graceful exit of the app.

Maybe this is 'working as designed', but I think it would be more logical to just exit without sending any more to stdout.

**Comment by erkyrath** [comment]
Thanks. Fizmo must be catching the interrupt signal and trying to do something with it. I will look into it.

**Comment by BroadcastGames** [comment]
yep, you are right, now when I look closer, I see:

    {"append":true, "content":[{ "style":"normal", "text":"Fizmo fatal error: Caught signal 2, aborting interpreter."}]},

Sorry I didn't catch that until just now.

**Comment by chrender** [comment]
By default fizmo will catch SIGSEGV, SIGTERM, SIGQUIT, SIGBUS, SIGILL and SIGINT. The latter one is generated whenever `CTRL+C`is pressed. Maybe you can open an issue on the fizmo github pages, if possible with a short description how it should behave.

**Comment by BroadcastGames** [comment]
I'll look at fizmo-console behavior and see how it compares (printing that same "Fizmo fatal error: Caught signal 2, aborting interpreter." type message) on deciding there.  I  I'll close this. Thank you.

**Comment by erkyrath** [comment]
Thanks for checking.
